### ISSUE TITLE
Project_dir does not exist

### ISSUE THREAD

**Issue by segerphilip** [santosfamilyfoundation/SantosGUI#53]
On first run of gui:
```Traceback (most recent call last):
  File "app.py", line 626, in <module>
    ex = MainGUI()
  File "app.py", line 119, in __init__
    if projects_exist():
  File "/home/philip/Documents/Git/SantosGUI/application/app_config.py", line 40, in projects_exist
    return (len(os.listdir(get_base_project_dir())) > 0)
OSError: [Errno 2] No such file or directory: '/home/philip/Documents/Git/SantosGUI/project_dir'

**Comment by runnersaw** [comment]
Fixed in #55
