### ISSUE TITLE
Retrieve Results Fails

### ISSUE THREAD

**Issue by youralien** [santosfamilyfoundation/SantosGUI#97]
```
retrieveResults called with identifier = 7df3e2ed-1593-4bea-8fb5-31997ca34306
Dumping "/Users/scope/Documents/SantosGUI/project_dir/PedsAtOlin/results/results.zip"...
Status Code: 500
Traceback (most recent call last):
  File "application/app.py", line 269, in retrieveResults
    with zipfile.ZipFile(os.path.join(results_dir, "results.zip"), "r") as zip_file:
  File "/Users/scope/miniconda2/envs/santosguiqt5/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/Users/scope/miniconda2/envs/santosguiqt5/lib/python2.7/zipfile.py", line 813, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file
Abort trap: 6
```

**Comment by youralien** [comment]
On the server, I got this error message
```
ERROR: Report was not generated for sending. Try re-running generation.
```

**Comment by runnersaw** [comment]
That is a generic error, and the `BadZipfile` error is handled now, so considering resolved.
